server:
  port: 8080

logging:
  level:
    root: INFO
    
spring:
  # redis 설정
  redis:
    host: redis
    port: 6379
    database: 0
    
  # Datasource 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: zxcv1234
    url: jdbc:mariadb://j9a106.p.ssafy.io:3306/oasys
    hikari:
      maximum-pool-size: 10
      connection-init-sql: SELECT 1
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
