server:
  port: 8081

spring:
  # Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
    # url: jdbc:mariadb://[서버주소]:[포트번호]/[DB명]
    url: jdbc:mysql://localhost:3306/oasys?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "file:./src/main/resources/env.yml"


logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace