server:
  port: 8080

logging:
  level:
    com.dolfin.oasys: DEBUG
    
spring:
  # redis 설정
  redis:
    template:
      keySerializer: org.springframework.data.redis.serializer.StringRedisSerializer
      valueSerializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
    host: redis
    port: 6379
    database: 0
    
  # Datasource 설정
  datasource:
    username: admin
    password: zxcv1234
    url: jdbc:mariadb://j9a106.p.ssafy.io:3306/oasys
    hikari:
      maximum-pool-size: 10
      connection-init-sql: SELECT 1
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
