server:
  port: 8080

spring:
  # redis 설정
  redis:
    host: redis
    port: 6379
    database: 0
    
  # Datasource 설정
  datasource:
    url: jdbc:mariadb://mariadb:3306/oasys
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000

  config:
    import: classpath:application-secrets.yml